version: '3'

services:
  frontend:
    build: ./frontend
    restart: on-failure
    networks:
      - proxy
  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      - mongo
    networks:
      - proxy
      - backend