version: '3'

services:
  frontend:
    build: ./frontend
    restart: on-failure
    networks:
      - proxy
    environment:
      - NODE_ENV=production
  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      - mongo
    networks:
      - proxy
      - backend
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongo:27017/md-live-slides