version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: on-failure
    depends_on:
      - frontend
      - backend
    networks:
      - proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/presentation.conf:ro
  mongo:
    image: mongo:4.1
    networks:
      - backend
    volumes:
      - mongodb:/data/db/

networks:
  proxy:
  backend:

volumes:
  mongodb: